"""
Django settings for ordersite project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vuw1=rk6o@tvf@sycrg65xy_7!l^+usoza-)vvpzs6xpgt140a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.authmid.AuthMiddleware',
]

ROOT_URLCONF = 'ordersite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            '/web/templates/'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ordersite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    '/web/static/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Settings below are manually added shortcuts with a "CRC_" prefix
"""
# public urls could be visited before logging in
CRC_PUBLIC_URLS = [
    '/login/',
    '/email_login/',
    '/email_send/',
]
# redirect here if not logged in
CRC_LOGIN_URL = '/login/'
# HOME page after logging in
CRC_LOGIN_HOME_URL = "/home/"
# KEY name to store user info in session
CRC_USER_SESSION_KEY = "crc_user"
# Server email address
CRC_EMAIL_ADDRESS = "2723473678@qq.com"
# Server email host
CRC_EMAIL_HOST, CRC_EMAIL_PORT = ("smtp.qq.com", 465)
# Server email password
CRC_EMAIL_AUTH_CODE = "nbbmdrbqfbwndejb"
# reflection between user's role and menu content
CRC_MENU_DICT = {
    "CUSTOMER": [
        {
            "id": "1",
            "text": "个人信息",
            "badge": "profile",
            "children": [
                {"text": "我的交易记录", "name": "customer_charge"},
                {'text': '我的订单', "name": "my_order"},
            ]
        },
        {
            "id": "2",
            "text": "用户中心",
            "badge": "client",
            "children": [
                {"text": "用户列表", "name": "customer"},
                {'text': '级别列表', "name": "customer_prior"},
            ]
        },
        {
            "id": "3",
            "text": "我的账户",
            "badge": "profile",
            "children": [
                {"text": "个人中心", "name": "my_profile"},
            ]
        },
    ],
    "ADMIN": [
        {
            "id": "1",
            "text": "用户信息",
            "badge": "client",
            "children": [
                {"text": "用户列表", "name": "customer"},
                {"text": "级别管理", "name": "customer_prior"},
            ]
        },
        {
            "id": "2",
            "text": "价格信息",
            "badge": "price",
            "children": [
                {"text": "价格梯度", "name": "price"},
            ]
        },
    ]
}
# public url
CRC_COMMON_URLS = ['home', 'login', 'logout', 'denied', 'email_login', 'email_send']
# user permissions on url
CRC_PERMISSION = {
    'ADMIN': {
        'home': {'text': '主页', 'parent': None, 'url': '/home/'},

        'customer': {'text': '用户管理', 'parent': None, 'url': '/customer/'},
        'customer_prior': {'text': "级别管理", 'parent': 'customer', 'url': "/customer/prior/"},
        'customer_add': {'text': '添加用户', 'parent': 'customer', 'url': '/customer/add/'},
        'customer_edit': {'text': '用户编辑', 'parent': 'customer', 'url': '/customer/edit/{}'},
        'customer_delete': {'text': '用户删除', 'parent': 'customer', 'url': '/customer/delete/{}'},

        'customer_charge': {'text': '用户缴费', 'parent': 'customer', 'url': '/customer/charge/{}'},
        'customer_charge_add': {'text': '添加缴费记录', 'parent': 'customer', 'url': '/customer/charge/{}/add'},

        'prior_edit': {'text': '级别编辑', 'parent': 'customer_prior', 'url': "/prior/edit/{}"},
        'prior_delete': {'text': '级别删除', 'parent': 'customer_prior', 'url': "/prior/delete/{}"},
        'prior_add': {'text': '级别添加', 'parent': 'customer_prior', 'url': "/prior/add/"},

        'price': {'text': "价格列表", 'parent': None, 'url': "/price/"},
        'price_add': {'text': "定价添加", 'parent': 'price', 'url': "/price/add/"},
        'price_edit': {'text': "定价编辑", 'parent': 'price', 'url': "/price/edit/"},
        'price_delete': {'text': "定价删除", 'parent': 'price', 'url': "/price/delete/"},
    },
    'CUSTOMER': {
        'home': {'text': '主页', 'parent': None, 'url': '/home/'},

        'customer': {'text': '用户管理', 'parent': None, 'url': '/customer/'},
        'customer_prior': {'text': "级别管理", 'parent': 'customer', 'url': "/customer/prior/"},
        'customer_charge': {'text': '用户缴费', 'parent': 'customer', 'url': '/customer/charge/{}/'},

        'my_order': {'text': "我的订单", 'parent': None, 'url': "/my_order/"},
        'my_order_add': {'text': "创建订单", 'parent': 'my_order', 'url': "/my_order/add/"},
        'my_order_revoke': {'text': "撤销订单", 'parent': 'my_order', 'url': "/my_order/revoke/"},

        'my_profile': {'text': "个人中心", 'parent': None, 'url': "/my_profile/"},
        'my_profile_reset': {'text': '密码重置', 'parent': 'my_profile', 'url': '/customer/reset/'},
    }
}

REDIS_QUEUE_NAME = "CRC_TASK_KEY"

try:
    from local_settings import *
except ImportError as e:
    pass
