# Generated by Django 3.2 on 2024-05-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=13, verbose_name='手机号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=13, verbose_name='手机号')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.administrator', verbose_name='创建者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('count', models.IntegerField(verbose_name='增加播放量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=20, verbose_name='等级头衔')),
                ('discount', models.SmallIntegerField(verbose_name='折扣值')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('charge_type', models.SmallIntegerField(choices=[(1, '客户充值'), (2, '人工扣费'), (3, '客户下单'), (4, '删除订单'), (5, '撤销订单')], verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('order_id', models.CharField(max_length=20, verbose_name='订单号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.administrator', verbose_name='管理员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='客户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[('1', '激活'), ('2', '删除')], default=1, verbose_name='状态')),
                ('status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '正在执行'), (3, '已完成'), (4, '失败')], default=1, verbose_name='订单状态')),
                ('oid', models.CharField(max_length=20, verbose_name='订单号')),
                ('url', models.CharField(max_length=255, verbose_name='视频地址')),
                ('count', models.IntegerField(verbose_name='播放量')),
                ('origin_view_count', models.CharField(default=0, max_length=32, verbose_name='视频原播放量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='费用')),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际收费')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('memo', models.TextField(verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='订单客户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='prior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.prior', verbose_name='等级'),
        ),
    ]
