# Generated by Django 3.2 on 2024-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20240505_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='order_id',
            field=models.CharField(max_length=20, null=True, verbose_name='订单号'),
        ),
    ]
