# Generated by Django 3.2 on 2024-05-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_transactionrecord_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.SmallIntegerField(choices=[(1, '充值'), (2, '扣款'), (3, '客户下单'), (4, '删除订单'), (5, '撤销订单')], verbose_name='交易类型'),
        ),
    ]
