# Generated by Django 3.2 on 2024-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20240510_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待执行'), (2, '正在执行'), (3, '已完成'), (4, '失败'), (5, '已撤单')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.SmallIntegerField(choices=[(1, '充值'), (2, '扣款'), (3, '下单'), (4, '删单'), (5, '撤单')], verbose_name='交易类型'),
        ),
    ]
