# Generated by Django 3.2 on 2024-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20240515_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.SmallIntegerField(choices=[(1, '充值'), (2, '扣款'), (3, '下单'), (4, '删单'), (5, '撤单单')], verbose_name='交易类型'),
        ),
    ]
