# Generated by Django 3.2 on 2024-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_transactionrecord_charge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='视频地址'),
        ),
    ]
