# Generated by Django 3.2 on 2024-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='电子邮箱'),
        ),
    ]
